services:
  mongodb:
    image: mongo:latest
    container_name: product-overview-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=product-overview-db

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
